services:
  typedb:
    image: typedb/typedb:3.8.1
    container_name: knowledgeplatform-typedb-v3
    ports:
      - "1729:1729"
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - typedb_data:/opt/typedb-all-linux/server/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: knowledgeplatform-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: unless-stopped
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  typedb_data:
  qdrant_storage: